import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import SessionProvider from '@/app/_components/SessionProvider'
import { redirect } from 'next/navigation'
import NavBar from '@/app/_components/NavBar'
import { Separator } from '@/components/ui/separator'
import SideBar from './_components/SideBar'
import {
  ResizablePanelGroup,
  ResizablePanel,
  ResizableHandle,
} from '@/components/ui/resizable'
import { auth } from '@/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  if (!session) {
    redirect('/api/auth/signin')
    return null
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className="flex h-screen flex-col">
            <NavBar />

            <Separator />
            <ResizablePanelGroup direction="horizontal">
              <ResizablePanel defaultSize={10}>
                <SideBar />
              </ResizablePanel>
              <ResizableHandle />
              <ResizablePanel defaultSize={90}>
                <main className="container py-16">{children}</main>
              </ResizablePanel>
            </ResizablePanelGroup>
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
